In [1]:
import numpy as np


In [2]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])


How many negative numbers are there?



In [4]:
(a < 0).shape

(12,)

How many positive numbers are there?



In [5]:
(a > 0).shape

(12,)

How many even positive numbers are there?



In [6]:
((a > 0) & (a % 2 == 0)).shape

(12,)

If you were to add 3 to each data point, how many positive numbers would there be?



In [7]:
plus_three = a + 3

In [8]:
(plus_three > 0).shape


(12,)

If you squared each number, what would the new mean and standard deviation be?



In [10]:
squared = a ** 2

In [11]:
squared.mean()

74.0

In [12]:
squared.std()

144.0243035046516

A common statistical operation on a dataset is centering. 
This means to adjust the data such that the center of the data is at 0. 
This is done by subtracting the mean from each data point. 
Center the data set.



In [17]:
mean = a.mean()

In [20]:
centering = a - mean
centering

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

Calculate the z-score for each data point. 
Recall that the z-score is given by:

In [21]:
(a - mean) / a.std()

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [26]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

 Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [28]:
sum_of_a = sum(a)
print(sum_of_a) 

55


Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [29]:
min_of_a = min(a)
print(min_of_a)

1


Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [31]:
max_of_a = max(a)
print(max_of_a)

10


Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [34]:
mean_of_a = sum(a) / len(a)
print(mean_of_a)

5.5


Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [36]:
product_of_a = 1
for item in a:
    product_of_a *= item
print(product_of_a)

3628800


Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [38]:
squares_of_a = [n**2 for n in a]
print(squares_of_a)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


Make a variable named odds_in_a. It should hold only the odd numbers

In [39]:
odds_in_a = [n for n in a if n %2 != 0]
print(odds_in_a)

[1, 3, 5, 7, 9]


Make a variable named evens_in_a. It should hold only the evens

In [41]:
evens_in_a = [n for n in a if n % 2 == 0]
print(evens_in_a)

[2, 4, 6, 8, 10]


In [42]:
b = np.array([
    [3, 4, 5],
    [6, 7, 8]
])

Use sum_of_b as the variable. **Hint, you'll first need to make sure 
that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

In [51]:
sum_of_b = b.sum()
print(sum_of_b)

33


min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1]) 

In [52]:
min_of_b = b.min()
print(min_of_b)

3


max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

In [54]:
max_of_b = b.max()
print(max_of_b)

8


|mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

In [55]:
mean_of_b = b.mean()
print(mean_of_b)

5.5


product_of_b = 1 for row in b: for number in row: product_of_b *= number

In [57]:
product_of_b = b.prod()
print(product_of_b)

20160


|squares_of_b = []for row in b: for number in row:
        squares_of_b.append(number**2)

In [58]:
squares_of_b = b ** 2
print(squares_of_b)

[[ 9 16 25]
 [36 49 64]]


odds_in_b = []for row in b:for number in row:if(number % 2 != 0):
            odds_in_b.append(number)

In [61]:
odds_in_b = b[b % 2 != 0]
print(odds_in_b)

[3 5 7]


evens_in_b = []for row in b:for number in row:if(number % 2 == 0):
            evens_in_b.append(number)

In [62]:
evens_in_b = b[b % 2 == 0]
print(evens_in_b)

[4 6 8]


Exercise 9 - print out the shape of the array b.

In [64]:
b.shape

(2, 3)

transpose the array b.

In [65]:
b.transpose()

array([[3, 6],
       [4, 7],
       [5, 8]])

reshape the array b to be a single list of 6 numbers. (1 x 6)

In [66]:
b.reshape(1,6)

array([[3, 4, 5, 6, 7, 8]])

reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [ ]:
b.reshape