In [109]:
import numpy as np


In [110]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])


How many negative numbers are there?

looking for all nums less than zero then use shape method to determine amt

In [111]:
(a < 0).shape

(12,)

How many positive numbers are there?

all nums greater than zero then use shape to get total

In [5]:
(a > 0).shape

(12,)

How many even positive numbers are there?

all num greater than zero and num modulus 2 for even, separate due to order of operations, then shape to get total

In [6]:
((a > 0) & (a % 2 == 0)).shape

(12,)

If you were to add 3 to each data point, how many positive numbers would there be?

first get array of each value plus 3, then get total using shape

In [7]:
plus_three = a + 3

In [8]:
(plus_three > 0).shape


(12,)

If you squared each number, what would the new mean and standard deviation be?

first get an array w/ each value squared, then use mean and std methods

In [10]:
squared = a ** 2

In [11]:
squared.mean()

74.0

In [12]:
squared.std()

144.0243035046516

A common statistical operation on a dataset is centering. 
This means to adjust the data such that the center of the data is at 0. 
This is done by subtracting the mean from each data point. 

Center the data set.

first find the mean, then subtract that from each value

In [17]:
mean = a.mean()

In [20]:
centering = a - mean
centering

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

Calculate the z-score for each data point. 

subtract mean from each value using variable created above, then divide by standard deviation

In [21]:
(a - mean) / a.std()

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [26]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

 Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

using sum function to get sum of a

In [28]:
sum_of_a = sum(a)
print(sum_of_a) 

55


Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [29]:
min_of_a = min(a)
print(min_of_a)

1


Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [31]:
max_of_a = max(a)
print(max_of_a)

10


Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [34]:
mean_of_a = sum(a) / len(a)
print(mean_of_a)

5.5


Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

using vanilla Python, looping thru array and multiplying each num against itself.

In [36]:
product_of_a = 1
for item in a:
    product_of_a *= item
print(product_of_a)

3628800


Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

using list comprehension to create a new list with each num squared

In [38]:
squares_of_a = [n**2 for n in a]
print(squares_of_a)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


Make a variable named odds_in_a. It should hold only the odd numbers

In [39]:
odds_in_a = [n for n in a if n %2 != 0]
print(odds_in_a)

[1, 3, 5, 7, 9]


Make a variable named evens_in_a. It should hold only the evens

In [41]:
evens_in_a = [n for n in a if n % 2 == 0]
print(evens_in_a)

[2, 4, 6, 8, 10]


In [42]:
b = np.array([
    [3, 4, 5],
    [6, 7, 8]
])

Use sum_of_b as the variable. **Hint, you'll first need to make sure 
that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

using numpy sum function to get total sum of b

In [51]:
sum_of_b = b.sum()
print(sum_of_b)

33


min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1]) 

In [52]:
min_of_b = b.min()
print(min_of_b)

3


max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

In [54]:
max_of_b = b.max()
print(max_of_b)

8


|mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

In [55]:
mean_of_b = b.mean()
print(mean_of_b)

5.5


product_of_b = 1 for row in b: for number in row: product_of_b *= number

In [57]:
product_of_b = b.prod()
print(product_of_b)

20160


|squares_of_b = []for row in b:

using numpy to create a new array with squared values

In [58]:
squares_of_b = b ** 2
print(squares_of_b)

[[ 9 16 25]
 [36 49 64]]


odds_in_b = []for row in b:for number in row:if(number % 2 != 0):
            odds_in_b.append(number)

In [61]:
odds_in_b = b[b % 2 != 0]
print(odds_in_b)

[3 5 7]


evens_in_b = []for row in b:for number in row:if(number % 2 == 0):
            evens_in_b.append(number)

In [62]:
evens_in_b = b[b % 2 == 0]
print(evens_in_b)

[4 6 8]


Exercise 9 - print out the shape of the array b.

In [64]:
b.shape

(2, 3)

transpose the array b.

In [65]:
b.transpose()

array([[3, 6],
       [4, 7],
       [5, 8]])

reshape the array b to be a single list of 6 numbers. (1 x 6)

In [66]:
b.reshape(1,6)

array([[3, 4, 5, 6, 7, 8]])

reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [67]:
b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [68]:
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

Find the min, max, sum, and product of c.

In [69]:
c.min

<function ndarray.min>

In [72]:
c.min()


1

In [73]:
c.max()

9

In [74]:
c.sum()

45

In [75]:
c.prod()

362880

Exercise 2 - Determine the standard deviation of c.

using numpy standard deviation function

In [76]:
c.std()

2.581988897471611

Exercise 3 - Determine the variance of c.

In [77]:
c.var()

6.666666666666667

#Exercise 4. Print out the shape of the array c

determining 3 by 3 shape of array

In [79]:
c.shape

(3, 3)

#Exercise 5. Transpose c and print out transposed result.

In [80]:
c.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

 Exercise 6. Get the dot product of the array c with c. 

using numpy to get dot product based on documentation

In [82]:
np.dot(c,c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

 Exercise 7. Write the code necessary to sum up the result of c times c transposed. Answer should be 261

In [90]:
sub = c * c.transpose()
sub.sum()


261

Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [91]:
sub = c * c.transpose()
sub.prod()

131681894400

In [92]:
d = np.array([
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
])

Exercise 1 - Find the sine of all the numbers in d

In [95]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

Exercise 2 - Find the cosine of all the numbers in d

In [96]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

Exercise 3 - Find the tangent of all the numbers in d

In [97]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

Exercise 4 - Find all the negative numbers in d

In [98]:
d[d < 0]

array([-90, -30, -45, -45])

Exercise 5 - Find all the positive numbers in d

In [99]:
d[d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

Exercise 6 - Return an array of only the unique numbers in d.

In [101]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

Exercise 7 - Determine how many unique numbers there are in d.

In [102]:
np.unique(d).shape

(11,)

Exercise 8 - Print out the shape of d.

In [103]:
d.shape

(3, 6)

Exercise 9 - Transpose and then print out the shape of d.

In [105]:
d.transpose().shape

(6, 3)

Exercise 10 - Reshape d into an array of 9 x 2

In [106]:
d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])